name: Artifact_Workflow

on: [push]

env:
  ARTIFACT_NAME: Artifact_01
  
jobs:
  create_artifact:
     name: create_artifact
     runs-on: ubuntu-latest
     steps:
         
       - name: Check out code
         uses: actions/checkout@v4

       - name: Upload Artifact for Linux
         uses: actions/upload-artifact@v4
         with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .
