name: Artifact_Workflow

on: [push]

env:
  ARTIFACT_NAME: Artifact_01
  
jobs:
  create_artifact:
     name: create_artifact
     runs-on: ubuntu-latest
     steps:
       - name: Check out code
         uses: actions/checkout@v1
       - name: build
