name: Artifact_Workflow

on: [push]

env:
  ARTIFACT_NAME: Artifact_01
  FILE_NAME: hello-server
  
jobs:
  create_artifact:
     name: create_artifact
     runs-on: ubuntu-latest
     steps:
       - name: Setup Go Environment
         uses: actions/setup-go@v5.0.0
         
       - name: Check out code
         uses: actions/checkout@v1
       
       - name: build ${{ env.FILE_NAME }} for ubuntu-latest
         run: go build ${{ env.FILE_NAME }}.go

        #- name: Build ${{ env.FILE_NAME }} for windows-latest
        #  run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go 

       - name: Upload Artifact for Linux
         uses: actions/upload-artifact@v1.0.0
         with:
            name: linux
            path: ./${{ env.FILE_NAME }}.exe

  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest
    needs: [create_artifact]
    steps: 
      - name: Check Out Code
        uses: actions/checkout@v1

      - name: Download Artifact
        uses: actions/download-artifact@v.1.0.0
        with: 
          name: linux

      - name: Test ${{ env.ARTIFACT_NAME }}
        run: test.sh
